"""Generate a flat docker-compose for a JuiceLab cohort.

Reads a roster file (one student handle per line, e.g. amelie, bobby,
chloe, dimitri) and emits docker/docker-compose.cohort.yml with one
juicelab-<handle> service per student, each on a distinct host port.

Also patches the DASHBOARD_CORS_ORIGINS variable so the dashboard
accepts events from each per-instance origin.

Usage:
    python docker/provision.py docker/roster.txt --port-base 3001 \\
        --output docker/docker-compose.cohort.yml

Then:
    cd docker
    docker compose -f docker-compose.yml -f docker-compose.cohort.yml \\
        --env-file .env up -d --build

The dashboard service from docker-compose.yml is reused; only the
juicelab-<handle> services are added by the cohort overlay file.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

LOGGER = logging.getLogger("provision")
SAFE_HANDLE = re.compile(r"^[a-z0-9][a-z0-9-]{0,30}$")

COHORT_HEADER = """\
# Generated by docker/provision.py - do NOT edit by hand.
# Combine with docker-compose.yml :
#   docker compose -f docker-compose.yml -f docker-compose.cohort.yml \\
#       --env-file .env up -d --build

name: juicelab

services:
"""

JUICELAB_TEMPLATE = """\
  juicelab-{handle}:
    build:
      context: ..
      dockerfile: docker/Dockerfile.juicelab
    image: juicelab:latest
    container_name: juicelab-{handle}
    environment:
      TEACHER_ADMIN_TOKEN: "${{TEACHER_ADMIN_TOKEN:?must be set in .env}}"
      JUICELAB_DASHBOARD_URL: "http://${{DASHBOARD_PUBLIC_HOST:-127.0.0.1}}:${{DASHBOARD_PORT:-5000}}"
      JUICELAB_COHORT_ID: "${{JUICELAB_COHORT_ID:?must be set in .env}}"
      JUICELAB_INSTANCE_LABEL: "{handle}"
      JUICELAB_DEFAULT_LANGUAGE: "${{JUICELAB_DEFAULT_LANGUAGE:-fr}}"
    ports:
      - "{port}:3000"
    networks: [juicelab_net]
    depends_on:
      dashboard:
        condition: service_healthy
    restart: unless-stopped
"""


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "roster",
        type=Path,
        help="Path to a text file with one student handle per line "
             "(comments # ok, blanks ignored)."
    )
    parser.add_argument(
        "--port-base",
        type=int,
        default=3001,
        help="First host port to map. Each student gets port_base + i. Default 3001."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("docker/docker-compose.cohort.yml"),
        help="Output path for the generated compose overlay."
    )
    parser.add_argument(
        "--print-cors",
        action="store_true",
        help="Also print the value to set as DASHBOARD_CORS_ORIGINS."
    )
    return parser.parse_args(argv)


def _read_roster(path: Path) -> list[str]:
    handles: list[str] = []
    with path.open("r", encoding="utf-8") as fh:
        for raw in fh:
            stripped = raw.split("#", 1)[0].strip()
            if not stripped:
                continue
            if not SAFE_HANDLE.match(stripped):
                LOGGER.warning("skipping invalid handle '%s' (must match %s)",
                               stripped, SAFE_HANDLE.pattern)
                continue
            handles.append(stripped)
    seen: set[str] = set()
    deduped: list[str] = []
    for handle in handles:
        if handle in seen:
            LOGGER.warning("duplicate handle '%s' ignored", handle)
            continue
        seen.add(handle)
        deduped.append(handle)
    return deduped


def _render(handles: list[str], port_base: int) -> tuple[str, list[str]]:
    chunks: list[str] = [COHORT_HEADER]
    cors_origins: list[str] = []
    for index, handle in enumerate(handles):
        port = port_base + index
        chunks.append(JUICELAB_TEMPLATE.format(handle=handle, port=port))
        cors_origins.append(f"http://127.0.0.1:{port}")
        cors_origins.append(f"http://localhost:{port}")
    chunks.append("\nnetworks:\n  juicelab_net:\n    external: false\n")
    return "".join(chunks), cors_origins


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
    args = _parse_args(argv if argv is not None else sys.argv[1:])

    if not args.roster.is_file():
        LOGGER.error("roster file not found: %s", args.roster)
        return 1

    handles = _read_roster(args.roster)
    if not handles:
        LOGGER.error("no valid handles in roster")
        return 1

    LOGGER.info("provisioning %d students starting at port %d",
                len(handles), args.port_base)

    compose, cors_origins = _render(handles, args.port_base)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(compose, encoding="utf-8")
    LOGGER.info("wrote %s (%d services)", args.output, len(handles))

    if args.print_cors:
        print()
        print("Add this to docker/.env so the dashboard accepts events from each instance:")
        print(f"DASHBOARD_CORS_ORIGINS={','.join(cors_origins)}")

    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
